server {
    listen 443 ssl;
    listen [::]:443 ssl; # all IPv6 interfaces
    server_name ajelloul.42.fr;

    ssl_certificate     /etc/nginx/ssl/nginx.crt;  
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.php index.html;

    #/about or /wp-admin
    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    #index.php wp-login.php
    location ~ \.php$ {
        # Loads standard FastCGI variables. REQUEST_METHOD(GET.POST) QUERY_STRING
        include fastcgi_params;
        # Send PHP requests to container wordpress port 9000.
        fastcgi_pass wordpress:9000;
        #/var/www/html/index.php PHP-FPM now knows exact file to execute.
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
