USE mysql;

ALTER USER 'root'@'localhost'
IDENTIFIED BY '${ROOT_PASS}';

CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}`;

CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%'
IDENTIFIED BY '${DB_PASS}';

GRANT ALL PRIVILEGES
ON `${MYSQL_DATABASE}`.*
TO '${MYSQL_USER}'@'%';

FLUSH PRIVILEGES;